marvel_inventory/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import uuid
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
import secrets
from flask_login import UserMixin, LoginManager
from flask_marshmallow import Marshmallow

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    username = db.Column(db.String(20), nullable = False, unique = True)
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = False, default="")
    g_auth_verify = db.Column(db.Boolean, default = False)
    token = db.Column(db.String, default="", unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)

    def __init__(self, email, username, id="", password="", token="", g_auth_verify = False):
        self.id = self.set_id()
        self.email = email
        self.username = username
        self.password = self.set_password(password)
        self.token = self.set_token(24)
        self.g_auth_verify = g_auth_verify

    def set_token(self, length):
        return secrets.token_hex(length)

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash

    def __repr__(self):
        return f"User: {self.username} has been added to the database"

class Hero(db.Model):
    id = db.Column(db.String, primary_key = True)
    name = db.Column(db.String(100), nullable = False, unique = True)
    power = db.Column(db.String, nullable = False)
    is_a_hero = db.Column(db.Boolean, nullable = False)
    comics_appeared_in = db.Column(db.Integer, nullable = False)
    description = db.Column(db.String(200), nullable = False)
    back_story = db.Column(db.String)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    owner = db.Column(db.String, db.ForeignKey("user.token"), nullable = False)
    
    def __init__(self, name, power, is_a_hero, comics_appeared_in, description, back_story, owner, id=""):
        self.name = name
        self.power = power
        self.is_a_hero = is_a_hero
        self.comics_appeared_in = comics_appeared_in
        self.description = description
        self.back_story = back_story
        self.owner = owner
        self.id = self.set_id()

    def __repr__(self):
        return f"Hero/Villain: {self.name} has been added!"
    
    def set_id(self):
        return (secrets.token_urlsafe())

# Creation of API Schema via the Marshmallow Object
class HeroSchema(ma.Schema):
    class Meta:
        fields = ["id", "name", "power", "is_a_hero", "comics_appeared_in", "description", "back_story"]

hero_schema = HeroSchema()
heroes_schema = HeroSchema(many=True)

marvel_inventory/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, IntegerField, RadioField
from wtforms.validators import DataRequired, Email
from .models import Hero

class UserLoginForm(FlaskForm):
    # email, password, submit_button
    email = StringField("Email: ", validators = [DataRequired(), Email()])
    username = StringField("Username: ", validators = [DataRequired()])
    password = PasswordField("Password: ", validators = [DataRequired()])
    submit_button = SubmitField()

class HeroForm(FlaskForm):
    # A Form for the User to fill out for their Hero/Villan
    name = StringField("Name of Hero or Villan: ", validators = [DataRequired()])
    power = StringField("The Super Power(s): ", validators = [DataRequired()])
    is_a_hero = RadioField("Hero or Villain? ", choices =[(True, "Hero"), (False, "Villain")], validators = ([DataRequired()]))
    comics_appeared_in = IntegerField("Comics They Have Appeared In: ", validators = ([DataRequired()]))
    description = StringField("Description: ")
    back_story = StringField("Their Back Story: ")
    submit_button = SubmitField()

marvel_inventory/__init__.py
from flask import Flask
from flask.templating import render_template
from sqlalchemy import orm
from config import Config
from .api.routes import api
from .site.routes import site
from .auth.routes import auth

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_cors import CORS
from marvel_inventory.models import db as root_db
from marvel_inventory.models import login_manager, ma
from marvel_inventory.helpers import JSONEncoder

app = Flask(__name__)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)
app.config.from_object(Config())

root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app.json_encoder = JSONEncoder

CORS(app)

marvel_inventory/api/routes.py
from flask import Blueprint, request,jsonify
from flask_migrate import current
from marvel_inventory.helpers import token_required
from marvel_inventory.models import db,User, Hero,hero_schema, heroes_schema

api = Blueprint("api", __name__, url_prefix="/api")

@api.route("/getdata")
def getdata():
    return {"some": "value", "foo":"bar"}

# Create Drone Endpoint -- CRUD -- Create, Read, Update, Delete
@api.route("/hero", methods = ["POST"])
@token_required
def create_hero(current_user_token):
    name = request.json["name"]
    power = request.json["power"]
    is_a_hero = request.json["is_a_hero"]
    comics_appeared_in = request.json["comics_appeared_in"]
    description = request.json["description"]
    back_story = request.json["back_story"]
    user_token = current_user_token.token

    print(F"BIG TESTER: {current_user_token.token}")

    hero = Hero(name, power, is_a_hero, comics_appeared_in, description, back_story, user_token=user_token)

    db.session.add(hero)
    db.session.commit()

    response = hero_schema.dump(hero)
    return jsonify(response)

# RETRIEVE ALL DRONES
@api.route("/hero", methods=["GET"])
@token_required
def get_heroes(current_user_token):
    owner = current_user_token.token
    heroes = Hero.query.filter_by(user_token = owner).all()
    response = heroes_schema.dump(heroes)
    return jsonify(response)

# RETRIEVE ONE DRONES
@api.route("/hero/<id>", methods=["GET"])
@token_required
def get_hero(current_user_token, id):
    owner = current_user_token.token
    if owner == current_user_token.token:
        hero = Hero.query.get(id)
        response = hero_schema.dump(hero)
        return jsonify(response)
    else:
        return jsonify({"message": "Valid Token Required"}), 401

@api.route('/hero/<id>', methods = ['POST','PUT'])
@token_required
def update_hero(current_user_token,id):
    hero = Hero.query.get(id) # GET HERO INSTANCE

    hero.name = request.json["name"]
    hero.power = request.json["power"]
    hero.is_a_hero = request.json["is_a_hero"]
    hero.comics_appeared_in = request.json["comics_appeared_in"]
    hero.description = request.json["description"]
    hero.back_story = request.json["back_story"]
    hero.user_token = current_user_token.token

    db.session.commit()
    response = hero_schema.dump(hero)
    return jsonify(response)


# DELETE DRONE ENDPOINT
@api.route('/hero/<id>', methods = ['DELETE'])
@token_required
def delete_hero(current_user_token, id):
    hero = Hero.query.get(id)
    db.session.delete(hero)
    db.session.commit()
    response = hero_schema.dump(hero)
    return jsonify(response)

marvel_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login.utils import login_required
"""
    Some arguments are specified when creating the Blueprint object.
    The first argument "site", is the blueprint name,
    which is used by Flask's routing mechanism.

    The second argument, __name__, is the Blueprint's import name,
    this is how flask locates the blueprint's resources.
"""

site = Blueprint("site", __name__, template_folder="site_templates")

@site.route("/")
def index():
    return render_template("index.html")

@site.route("/profile")
@login_required
def profile():
    return render_template("profile.html")

marvel_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="Description" content="Enter your description here"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link rel="stylesheet" href="../static/css/main.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
        <title>Super Hero Maker</title>
    </head>
    <body>
        <!-- NavBar Here -->
        <nav class="ct-nav">
            <div>
                <!-- <img src="../static/images/Coding Drones Logo.png" alt="Coding Drones Logo"> -->
            </div>
            <!-- Nav Items -->
            <div>
                <ul id="horizontal-list">
                    <a href="{{ url_for('site.index') }}">
                        <li>Home Page</li>
                    </a>
                    {% if current_user.is_authenticated %}
                    <a href="{{ url_for('auth.hero') }}">
                        <li>Make/View Heroes/Villains</li>
                    </a>
                    <a href="{{ url_for('site.profile') }}">
                        <li>Profile</li>
                    </a>
                    <a href="{{ url_for('auth.logout') }}">
                        <li>Log Out</li>
                    </a>
                    {% else %}
                    <a href="{{ url_for('auth.hero') }}">
                        <li>View Heroes/Villains</li>
                    </a>
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <!-- End of Nav -->
        {% block content %}
        {% endblock content %}
        <div class="container">
            <div class="col">
                <h1>FOOTER INFORMATION</h1>
            </div>
        </div>
    </body>
</html>

marvel_inventory/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "place email here: ") }}
        </fieldset>
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "place username here: ") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "place password here: ") }}
        </fieldset>
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>

marvel_inventory/templates/heroform.html
<!-- HTML produced by the Flask -->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="name-field">
            {{ form.name.label }}
            {{ form.name(class = "form-control", placeholder = "place name here: ") }}
        </fieldset>
        <fieldset id="power-field">
            {{ form.power.label }}
            {{ form.power(class = "form-control", placeholder = "place power here: ") }}
        </fieldset>
        <fieldset id="is_a_hero-field">
            {{ form.is_a_hero.label }}
            {{ form.is_a_hero() }}
        </fieldset>
        <fieldset id="comics_appeared_in-field">
            {{ form.comics_appeared_in.label }}
            {{ form.comics_appeared_in(class = "form-control", placeholder = "place comics appeared in here: ") }}
        </fieldset>
        <fieldset id="description-field">
            {{ form.description.label }}
            {{ form.description(class = "form-control", placeholder = "place description here: ") }}
        </fieldset>
        <fieldset id="back_story-field">
            {{ form.back_story.label }}
            {{ form.back_story(class = "form-control", placeholder = "place back story here: ") }}
        </fieldset>
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>

marvel_inventory/templates/signinform.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "place email here: ") }}
        </fieldset>
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "place username here: ") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "place password here: ") }}
        </fieldset>
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>